/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ffos.tatacuvalica.view;

import ffos.tatacuvalica.controller.ObradaDijete;
import ffos.tatacuvalica.controller.ObradaTata;
import ffos.tatacuvalica.model.Dijete;
import ffos.tatacuvalica.model.Tata;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author anja0
 */
public class FormaTata extends javax.swing.JFrame implements ViewAktivnosti{

    
    private ObradaTata obradaTata;
    private ObradaDijete obradaDijete;
    /**
     * Creates new form FormaTata
     */
     public FormaTata() {
        initComponents();
        setTitle("Tate čuvalice");
        obradaTata = new ObradaTata();
        obradaDijete = new ObradaDijete();
        ucitajPodatke(); 
        ucitajDjecu();
    }
     
    public void ucitajDjecu() {
        DefaultListModel<Dijete> s = new DefaultListModel<>();
        s.addAll(obradaDijete.read());
        lstDijete.setModel(s);
        lstDijete.repaint();
    }
    
    @Override
    public void ucitajPodatke(){
        DefaultListModel<Tata> o = new DefaultListModel<>();
        o.addAll(obradaTata.read());
        lstEntiteti.setModel(o);
        lstEntiteti.repaint();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreate = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstEntiteti = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIme = new javax.swing.JTextField();
        txtPrezime = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDatumRodjenja = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstDijeteTata = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstDijete = new javax.swing.JList<>();
        btnDodaj = new javax.swing.JButton();
        btnOduzmi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        lstEntiteti.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstEntitetiValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstEntiteti);

        jLabel1.setText("Ime");

        jLabel2.setText("Prezime");

        txtIme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImeActionPerformed(evt);
            }
        });

        txtPrezime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrezimeActionPerformed(evt);
            }
        });

        jLabel3.setText("Datum rođenja");

        txtDatumRodjenja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDatumRodjenjaActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(lstDijeteTata);

        jScrollPane3.setViewportView(lstDijete);

        btnDodaj.setText("<");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnOduzmi.setText(">");
        btnOduzmi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOduzmiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnCreate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(txtIme)
                            .addComponent(txtPrezime)
                            .addComponent(txtDatumRodjenja, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDodaj, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnOduzmi, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDatumRodjenja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCreate)
                            .addComponent(btnUpdate)
                            .addComponent(btnDelete)))
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3))
                .addGap(61, 61, 61))
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(btnDodaj)
                .addGap(18, 18, 18)
                .addComponent(btnOduzmi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        obradaTata.setNew();
        List<Dijete> dijete = new ArrayList<>();
        for(int i = 0; i < lstDijeteTata.getModel().getSize(); i++) {
            dijete.add(lstDijeteTata.getModel().getElementAt(i));
        }
        obradaTata.setPodaci(txtIme.getText(), txtPrezime.getText(), txtDatumRodjenja.getText(), dijete);
        try {
            obradaTata.create();
            ucitajPodatke();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());}
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
         if (lstEntiteti.getSelectedValue() == null) {
            return;
        }
        obradaTata.setEntitet(lstEntiteti.getSelectedValue());
        List<Dijete> dijete = new ArrayList<>();
        for(int i = 0; i < lstDijeteTata.getModel().getSize(); i++) {
            dijete.add(lstDijeteTata.getModel().getElementAt(i));
        }
        obradaTata.setPodaci(txtDatumRodjenja.getText(), txtIme.getText(), txtPrezime.getText(), dijete);
        try {
            obradaTata.update();
            ucitajPodatke();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (lstEntiteti.getSelectedValue() == null) {
            return;
        }
        obradaTata.setEntitet(lstEntiteti.getSelectedValue());
        try {
            obradaTata.delete();
            ucitajPodatke();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtImeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImeActionPerformed

    private void txtPrezimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrezimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrezimeActionPerformed

    private void txtDatumRodjenjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDatumRodjenjaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDatumRodjenjaActionPerformed

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed
        DefaultListModel<Dijete> dt;
        if(lstEntiteti.getSelectedValue() == null){
            return;
        }
        if (lstEntiteti.getSelectedValue().getDijete()!= null) {
            dt = (DefaultListModel<Dijete>) lstDijeteTata.getModel();
        } else {
            dt = new DefaultListModel<>();
            lstDijeteTata.setModel(dt);
        }

        if (lstEntiteti.getSelectedValue().getDijete()== null) {
            lstEntiteti.getSelectedValue().setDijete(new ArrayList<>());
        }
        for (Dijete d : lstDijete.getSelectedValuesList()) {
            if (!dijeteNaCuvanju(dt, d)) {
                dt.addElement(d);
            }
        }
        lstDijeteTata.repaint();
    }//GEN-LAST:event_btnDodajActionPerformed

    private void lstEntitetiValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstEntitetiValueChanged
        // Lista tata
        //Listu tata već imaš jer si zadala u Type Paramteres <Tata>
        //Ovo je postavljeno za odabir 
        if (evt.getValueIsAdjusting() || lstEntiteti.getSelectedValue() == null) {
            return;
        }
        txtIme.setText(lstEntiteti.getSelectedValue().getIme());
        txtPrezime.setText(lstEntiteti.getSelectedValue().getPrezime());
        txtDatumRodjenja.setText(lstEntiteti.getSelectedValue().getDatumRodjenja().toString());

        // Postavljanje liste djece koju čuva otac
        DefaultListModel<Dijete> m = new DefaultListModel<>();
        if (lstEntiteti.getSelectedValue().getDijete()!= null) {
            m.addAll(lstEntiteti.getSelectedValue().getDijete());
        }
        lstDijeteTata.setModel(m);
        lstDijeteTata.repaint();
    }//GEN-LAST:event_lstEntitetiValueChanged

    private void btnOduzmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOduzmiActionPerformed
        DefaultListModel<Dijete> dt = (DefaultListModel<Dijete>) lstDijeteTata.getModel();
        for (Dijete d : lstDijete.getSelectedValuesList()) {
            dt.removeElement(d);
        }

        lstDijeteTata.repaint();
        lstDijete.repaint();
    }//GEN-LAST:event_btnOduzmiActionPerformed

    //samo kopiraj
     private boolean dijeteNaCuvanju(DefaultListModel<Dijete> dt, Dijete d) {
        for (int i = 0; i < dt.size(); i++) {
            if (dt.get(i).getSifra() == d.getSifra()) {
                return true;
            }
        }
        return false;
    }
    // NE ZABORAVI OBRISATI MAIN METODU

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnOduzmi;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<Dijete> lstDijete;
    private javax.swing.JList<Dijete> lstDijeteTata;
    private javax.swing.JList<Tata> lstEntiteti;
    private javax.swing.JTextField txtDatumRodjenja;
    private javax.swing.JTextField txtIme;
    private javax.swing.JTextField txtPrezime;
    // End of variables declaration//GEN-END:variables
}
