/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package alabak_kol2.view;

import alabak_kol2.controller.ObradaMjesto;
import alabak_kol2.controller.ObradaSkola;
import alabak_kol2.controller.ObradaUcenik;
import com.github.javafaker.Faker;
import java.util.Date;

/**
 *
 * @author anja0
 */
public class Izbornik extends javax.swing.JFrame {

    /**
     * Creates new form Izbornik
     */
    public Izbornik() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSkola = new javax.swing.JButton();
        btnMjesto = new javax.swing.JButton();
        btnUcenik = new javax.swing.JButton();
        btnCrudSkola = new javax.swing.JButton();
        btnCrudMjesto = new javax.swing.JButton();
        btnCrudUcenik = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSkola.setText("3.1.");
        btnSkola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkolaActionPerformed(evt);
            }
        });

        btnMjesto.setText("3.2.");
        btnMjesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMjestoActionPerformed(evt);
            }
        });

        btnUcenik.setText("3.3.");
        btnUcenik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUcenikActionPerformed(evt);
            }
        });

        btnCrudSkola.setText("3.4.");
        btnCrudSkola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrudSkolaActionPerformed(evt);
            }
        });

        btnCrudMjesto.setText("3.5.");
        btnCrudMjesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrudMjestoActionPerformed(evt);
            }
        });

        btnCrudUcenik.setText("3.6.");
        btnCrudUcenik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrudUcenikActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMjesto, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSkola, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUcenik, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCrudUcenik, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCrudSkola, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCrudMjesto, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSkola)
                    .addComponent(btnCrudSkola))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMjesto)
                    .addComponent(btnCrudMjesto))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUcenik)
                    .addComponent(btnCrudUcenik))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSkolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkolaActionPerformed
        ObradaSkola os = new ObradaSkola();
        Faker faker = new Faker();
        
        for(int i=0;i<58;i++){
            os.setNew();
            os.setPodaci(faker.team().name(), faker.team().state());
            try {
                os.create();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_btnSkolaActionPerformed

    private void btnMjestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMjestoActionPerformed
         ObradaMjesto os = new ObradaMjesto();
        Faker faker = new Faker();
        
        for(int i=0;i<120;i++){
            os.setNew();
            os.setPodaci(faker.country().capital());
            try {
                os.create();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_btnMjestoActionPerformed

    private void btnUcenikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUcenikActionPerformed
       ObradaUcenik ou = new ObradaUcenik();
        Faker faker = new Faker();
        
        for(int i=0;i<47;i++){
            ou.setNew();
            ou.setPodaci(faker.date().birthday().toString(), faker.name().firstName(), faker.name().lastName(), null, null);
            try {
                ou.create();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_btnUcenikActionPerformed

    private void btnCrudSkolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrudSkolaActionPerformed
        new FormaSkola().setVisible(true);
    }//GEN-LAST:event_btnCrudSkolaActionPerformed

    private void btnCrudMjestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrudMjestoActionPerformed
        new FormaMjesto().setVisible(true);
    }//GEN-LAST:event_btnCrudMjestoActionPerformed

    private void btnCrudUcenikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrudUcenikActionPerformed
        new FormaUcenik().setVisible(true);
    }//GEN-LAST:event_btnCrudUcenikActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrudMjesto;
    private javax.swing.JButton btnCrudSkola;
    private javax.swing.JButton btnCrudUcenik;
    private javax.swing.JButton btnMjesto;
    private javax.swing.JButton btnSkola;
    private javax.swing.JButton btnUcenik;
    // End of variables declaration//GEN-END:variables
}
