/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ffos.alabak_kol2b.view;

import ffos.alabak_kol2b.controller.ObradaSkola;
import com.github.javafaker.Faker;
import ffos.alabak_kol2b.controller.ObradaUcenik;
import ffos.alabak_kol2b.model.Skola;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author anja0
 */
public class Izbornik extends javax.swing.JFrame{

    /**
     * Creates new form Izbornik
     */
    public Izbornik() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSkola = new javax.swing.JButton();
        btnUcenik = new javax.swing.JButton();
        btnCrudSkola = new javax.swing.JButton();
        btnCrudUcenik = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnSkola.setText("3.1.");
        btnSkola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSkolaActionPerformed(evt);
            }
        });

        btnUcenik.setText("3.2.");
        btnUcenik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUcenikActionPerformed(evt);
            }
        });

        btnCrudSkola.setText("3.3.");
        btnCrudSkola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrudSkolaActionPerformed(evt);
            }
        });

        btnCrudUcenik.setText("3.4.");
        btnCrudUcenik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrudUcenikActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnUcenik)
                    .addComponent(btnSkola))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCrudSkola)
                    .addComponent(btnCrudUcenik))
                .addGap(88, 88, 88))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSkola)
                    .addComponent(btnCrudSkola))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUcenik)
                    .addComponent(btnCrudUcenik))
                .addContainerGap(131, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSkolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSkolaActionPerformed
        ObradaSkola os = new ObradaSkola();
        Faker faker = new Faker();
        
        for(int i=0;i<200;i++){
            os.setNew();
            os.setPodaci(faker.name().fullName(), faker.ancient().god());
            try {
                os.create();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_btnSkolaActionPerformed

    private void btnUcenikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUcenikActionPerformed
         ObradaUcenik ou = new ObradaUcenik();
        Faker faker = new Faker();
        ObradaSkola os = new ObradaSkola();
        List<Skola> skole = os.read();
        
        for(int i=0;i<17;i++){
            ou.setNew();
            List <Skola> sk = new ArrayList<>();
            sk.add(skole.get(i+1));
            ou.setPodaci(faker.date().birthday().toString(), faker.name().firstName(), faker.name().lastName(), sk);
            try {
                ou.create();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_btnUcenikActionPerformed

    private void btnCrudSkolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrudSkolaActionPerformed
         new FormaSkola().setVisible(true);
    }//GEN-LAST:event_btnCrudSkolaActionPerformed

    private void btnCrudUcenikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrudUcenikActionPerformed
        new FormaUcenik().setVisible(true);
    }//GEN-LAST:event_btnCrudUcenikActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrudSkola;
    private javax.swing.JButton btnCrudUcenik;
    private javax.swing.JButton btnSkola;
    private javax.swing.JButton btnUcenik;
    // End of variables declaration//GEN-END:variables
}
